# Generated by Django 3.1.1 on 2020-09-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagem'),
        ),
    ]
