# Generated by Django 3.1.1 on 2020-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200925_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='course',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição curta'),
        ),
    ]
